name: "Hello World Workflow"

on:
    push:
        branches:
            - main
            - add-actions
    workflow_dispatch:


jobs:
    helloworld:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "Hello World from GitHub Actions!"
              shell: bash

